### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by abcLeoLee** [againerju/tcg_recognition#3]
Dear Author,

Could you please share the datasets used in your research "Traffic Control Gesture Recognition for Autonomous Vehicles." And I would like to ask could you please give me your new email. Thank you very much.

Best regards

**Comment by againerju** [comment]
Dear @abcLeoLee ,

thank you for the message. For dataset access, please follow the guidlines in the README, thank you!

Best regards
Julian

**Comment by againerju** [comment]
Closed.
